### ISSUE TITLE
Problem with installing cellKey package.

### ISSUE THREAD

**Issue by kalleluunjast** [sdcTools/protoTestCensus#3]
Installation of said package is unsuccesful. Logs of installing the package using .tar.gz file and 
directly from github are below.
[log_alternative.txt](https://github.com/sdcTools/protoTestCensus/files/3026360/log_alternative.txt)
[log_using_tar_gz.txt](https://github.com/sdcTools/protoTestCensus/files/3026361/log_using_tar_gz.txt)

**Comment by bernhard-da** [comment]
hi @kalleluunjast 

thx for reporting this. i was able to partly reproduce and modified the instructions in this repo to install the package. The reason is that I had to update the sdcTable package and thus also the cell key package that relies on it. So the installation instructions have slightly changed. It did update the instructions but forgot to push them :( But not they are up to date and I just tested with a vanilla windows-installation (in vmware)

However, please also make sure that you use an up-to-date R version. It also seems as if you installed R with administrative rights and want to update/install without these rights. That's why you get the `will not be updated` messages.

So, I'd kindly ask you to try again with the following code (copied from the main page):

```
rm(list=ls())
update.packages(ask=FALSE)
install.packages("devtools")
remotes::install_github(
  repo = "sdcTools/cellKey",
  ref = "v0.16.1",
  dependencies = TRUE,
  build_opts = "--no-resave-data",
  force = TRUE
)
```

this should install all required dependencies.

if you have any more errors, please post the output of

```
devtools::session_info()
```

here. thx.

**Comment by kalleluunjast** [comment]
It didn't work. I think i don't have the permission to update some libraries and that is the reason installaton is unsuccesful.

> devtools::session_info()
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘processx’

**Comment by bernhard-da** [comment]
@kalleluunjast the problem seems to be with the `processx` package that is a dependency of the devtools pkg.

what is the output of the following command?
 
```install.packages("processx")```

**Comment by kalleluunjast** [comment]
Package was installed successfully.
> install.packages("processx")
Installing package into ‘C:/Tarkvara/R/R_Libs’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/processx_3.3.0.zip'
Content type 'application/zip' length 310200 bytes (302 KB)
downloaded 302 KB

package ‘processx’ successfully unpacked and MD5 sums checked

**Comment by kalleluunjast** [comment]
I don't get it. Now the installation of package was successful. That solved the problem, although I have no idea why. Thanks! :)

**Comment by bernhard-da** [comment]
@kalleluunjast  :+1: great that it is solved now!

**Comment by pnicky** [comment]
Hi, I cannot install the package.
I have:

```
> rm(list=ls())
> install.packages("devtools")
```

I downloaded cellKey-0.16.1
Then:
```
> remotes::install_local(
>   path = 'C:/Program Files/R/R-3.5.3/library/cellKey-0.16.1',
>   dependencies = TRUE,
>   build_opts = "--no-resave-data",
>   force = TRUE
> )

```
 `library(cellKey)`
Error message:
> library(cellKey)
Error: package or namespace load failed for ‘cellKey’:
 object ‘add_nodes’ is not exported by 'namespace:sdcTable'

I have data.table already:
> library(data.table)

Can you please help? Thanks!

**Comment by bernhard-da** [comment]
@kalleluunjast 

please update your R installation first (`update.packages(ask = F)`). you have an old version of `sdcTable` installed. This is why you get the error.

**Comment by pnicky** [comment]
Thanks for this! Actually, I did this, but I still have some errors:
Sorry in case it is something obvious. It's my home PC, in workplace, it's fine.

> update.packages(ask = F)
Warning: package 'boot' in library 'C:/Program Files/R/R-3.5.3/library' will not be updated
Warning: package 'cluster' in library 'C:/Program Files/R/R-3.5.3/library' will not be updated
Warning: package 'MASS' in library 'C:/Program Files/R/R-3.5.3/library' will not be updated
Warning: package 'nlme' in library 'C:/Program Files/R/R-3.5.3/library' will not be updated

  There are binary versions available but the source versions are later:
         binary  source needs_compilation
cluster   2.0.8   2.0.9              TRUE
nlme    3.1-137 3.1-139              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/cluster_2.0.8.zip'
Content type 'application/zip' length 589482 bytes (575 KB)
downloaded 575 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/nlme_3.1-137.zip'
Content type 'application/zip' length 2346045 bytes (2.2 MB)
downloaded 2.2 MB

package ‘cluster’ successfully unpacked and MD5 sums checked
package ‘nlme’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\NiXXX\AppData\Local\Temp\RtmpcbPDCf\downloaded_packages

**Comment by pnicky** [comment]
One more comment: I copied and pasted cluster and nlme from Local/Temp... to the appropriate R library.

**Comment by bernhard-da** [comment]
@pnicky i think that your R version was installed with admin-rights initially and you are trying to update the package without admin rights. thus, these "base" packages could not be updated ...

perhaps run `update.packages()` with admin rights?

**Comment by pnicky** [comment]
Thank you, Bernhard. It's better but still not good. It seems I cannot use this package at home. (also, it's funny that I am admin on my home PC... but the ask=F was not good)

**Comment by bernhard-da** [comment]
what's the error message now?

**Comment by pnicky** [comment]
Thanks, I guess my problem is this: https://stackoverflow.com/questions/15363076/error-in-gzfilefile-wb-cannot-open-the-connection-or-compressed-file
I try to change the working directory.

**Comment by pnicky** [comment]
This helped but not perfectly. I have DESCRIPTION in the folder, and still, it isn't working:
* installing *source* package 'cellKey' ...
Error in file(file, if (append) "a" else "w") : 
  (converted from warning) cannot open file 'C:/Users/NiXX/Documents/R/win-library/3.5/cellKey/DESCRIPTION': No such file or directory
ERROR: installing package DESCRIPTION failed for package 'cellKey'

**Comment by bernhard-da** [comment]
@pnicky just a guess in the blue. but you wrote you were using

```
remotes::install_local(
  path = 'C:/Program Files/R/R-3.5.3/library/cellKey-0.16.1',
  ...
)
```
if `'C:/Program Files/R/R-3.5.3/library/cellKey-0.16.1` is the path to which you extracted the downloaded file, this might not work this is very likely your R library. 

i would try to just download the file and run

```
remotes::install_local(
  path = 'c:/path/to/cellkey.zip',
  ...
)
```
