### ISSUE TITLE
Memory size problems

### ISSUE THREAD

**Issue by iecainf** [sdcTools/protoTestCensus#4]
Is there an estimate of the size of needed  memory based on the number of perturbed variables?. Is there any internal limit in the algorithm implementation?. We need to  perturb a 32 variables dataset .

**Comment by ppdewolf** [comment]
What method are you referring to? Targeted Record Swapping or Cell Key Method? 

What software are you referring to? One of the Argus packages or one of the R-packages?

**Comment by iecainf** [comment]
We use the Cell Key method ,R-package

Thank you

**Comment by bernhard-da** [comment]
@iecainf there is no explicit limit and it is difficult to estimate memory requirements as it very much depends on the (hierarchical) structure of your table. it is probably best to experiment a bit with a subset of variables first.

**Comment by iecainf** [comment]
Thank you
